AgriFood/Models/Order.cs
using System;
namespace AgriFood.Models
{
    public class Order
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public DateTime OrderDate { get; set; }

        public string CustomerId { get; set; }
        public ApplicationUser Customer { get; set; }

        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

AgriFood/Controllers/OrdersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AgriFood.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AgriFood.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Farmer")]
        public async Task<IActionResult> FarmerOrders(string FarmerId)
        {
            if (FarmerId != UserId())
            {
                return NotFound();
            }

            var applicationDbContext = _context.Orders
                                               .Include(o => o.Customer)
                                               .Include(o => o.Product)
                                               .Where(o => o.Product.FarmerId == FarmerId)
                                               .OrderByDescending(o => o.OrderDate);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Farmer, Customer")]
        public async Task<IActionResult> CustomerOrders(string CustomerId)
        {
            if (CustomerId != UserId())
            {
                return NotFound();
            }

            var applicationDbContext = _context.Orders
                                               .Include(o => o.Product)
                                               .Where(o => o.CustomerId == CustomerId)
                                               .OrderByDescending(o => o.OrderDate);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Farmer, Customer")]
        public IActionResult Create()
        {
            var model = new Order { };
            return PartialView("_OrderModalPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Farmer, Customer")]
        public async Task<IActionResult> Create([Bind("ID,Address,Amount,OrderDate,Price,CustomerId,ProductId")] Order order)
        {

            if(order.Amount == 0)
            {
                ModelState.AddModelError("Amount", "You cannot give order as 0 amount");
            }

            var product =  await _context.Products.FindAsync(order.ProductId);
            var diff_amount = product.Amount - order.Amount;

            if(diff_amount < 0)
            {
                ModelState.AddModelError("Amount", "You cannot take this product because product not enought for your order amount");
            }
            
            if (ModelState.IsValid)
            {
                order.OrderDate = DateTime.Now;
                order.Price = product.Price * order.Amount;
                order.CustomerId = UserId();
                _context.Add(order);

                product.Amount = diff_amount;
                _context.Update(product);

                await _context.SaveChangesAsync();
                return PartialView("_OrderModalPartial", order);
            }

            ViewBag.ProductPrice = product.Price;
            ViewBag.ProductId = order.ProductId;
            
            return PartialView("_OrderModalPartial", order);
        }

        private string UserId()
        {
            return _userManager.GetUserId(HttpContext.User);
        }
    }
}

AgriFood/Views/Orders/CustomerOrders.cshtml
@model IEnumerable<Order>

@{
    ViewData["Title"] = "My Orders";
}

<h2 class="text-center text-info mt-3">My Orders</h2>
<hr />
@await Html.PartialAsync("_OrderList", Model)

AgriFood/Views/Orders/FarmerOrders.cshtml
@model IEnumerable<Order>

@{
    ViewData["Title"] = "Incoming Orders";
}

<h2 class="text-center text-info mt-3">My Incoming Orders</h2>
<hr />
@await Html.PartialAsync("_OrderList", Model)

AgriFood/Views/Orders/_OrderList.cshtml
@model IEnumerable<Order>

<div class="shadow-lg p-3 mb-5 mt-5 bg-white rounded">
    <div class="table-responsive-md">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">
                        Product Name
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Amount)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.OrderDate)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            $@Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrderDate)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AgriFood/Views/Orders/_OrderModalPartial.cshtml
@model Order

<div class="modal fade" id="add-order" tabindex="-1" role="dialog" aria-labelledby="addOrderLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addOrderLabel">Add Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Create" asp-controller="Orders">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    <div>Unit Price: $<strong id="product-unit-price">@ViewBag.ProductPrice</strong></div>
                    <br />
                    <div>Total Price: $<strong id="order-total-price">0</strong></div>
                    <br />
                    <div class="form-group">
                        <input asp-for="ProductId" class="form-control" hidden />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-save="modal">Apply</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#Amount").keyup(function() {
        let product_unit_price = parseInt($('#product-unit-price').html());
        $('#order-total-price').html( product_unit_price * $(this).val());
    });
</script>