AgriFood/Controllers/FarmerController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AgriFood.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace AgriFood.Controllers
{
    public class FarmerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FarmerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Details(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            ViewBag.Farmer = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            ViewBag.IsProductOwn = IsProductOwn(id);
            var Products = _context.Products.Include(p => p.Farmer)
                                            .Where(p => p.FarmerId == id & p.IsActive)
                                            .OrderByDescending(p => p.CreatedDate);
            return View(await Products.ToListAsync());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private Boolean IsProductOwn(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            return userId == id ? true : false;
        }
    }
}

AgriFood/Controllers/ProductsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AgriFood.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;
using AgriFood.ViewModels;

namespace AgriFood.Controllers
{
    [Authorize(Roles = "Farmer")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id, string FarmerId)
        {
            if (id == null & FarmerId != UserId())
            {
                return NotFound();
            }

            ViewBag.IsProductOwn = IsProductOwn(FarmerId);
            var product = await _context.Products
                .Include(p => p.Farmer).Where(i => i.FarmerId == FarmerId)
                .FirstOrDefaultAsync(m => m.ID == id);
            return product == null ? NotFound() : (IActionResult)View(product);
        }
        
        public IActionResult Create(string FarmerId)
        {
            return FarmerId != UserId() ? NotFound() : (IActionResult)View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description,IsActive,Amount,Image,Price,FarmerId")] ProductCreateEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    FarmerId = UserId(),
                    CreatedDate = DateTime.Now,
                    Title = model.Title,
                    Description = model.Description,
                    IsActive = model.IsActive,
                    Amount = model.Amount,
                    Price = model.Price
                };
                if (model.Image != null && model.Image.Length > 0)
                { 
                    using (var memoryStream = new MemoryStream())
                    {
                        await model.Image.CopyToAsync(memoryStream);
                        product.Image = memoryStream.ToArray();
                    }
                }
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = product.ID });
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id, string FarmerId)
        {
            if (id == null & FarmerId != UserId())
            {
                return NotFound();
            }

            ProductCreateEditViewModel model;

            var product = await _context.Products
                                        .Where(i => i.FarmerId == UserId())
                                        .FirstOrDefaultAsync(m => m.ID == id);

            if (product == null)
            {
                return NotFound();
            }

            model = new ProductCreateEditViewModel
            {
                ID = product.ID,
                Title = product.Title,
                Description = product.Description,
                IsActive = product.IsActive,
                Amount = product.Amount,
                Price = product.Price
            };

            ViewBag.Image = product.Image;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description,IsActive,Amount,Image,Price,FarmerId")] ProductCreateEditViewModel model)
        {
            if (id != model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var product = await _context.Products
                                    .Where(i => i.FarmerId == UserId())
                                    .FirstOrDefaultAsync(m => m.ID == id);
                try
                {
                    product.FarmerId = UserId();
                    product.ID = model.ID;
                    product.Title = model.Title;
                    product.Description = model.Description;
                    product.IsActive = model.IsActive;
                    product.Amount = model.Amount;
                    product.Price = model.Price;

                    if (model.Image != null && model.Image.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await model.Image.CopyToAsync(memoryStream);
                            product.Image = memoryStream.ToArray();
                        }
                    }

                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(model.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = product.ID });
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id, string FarmerId)
        {
            if (id == null & FarmerId != UserId())
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Farmer).Where(i => i.FarmerId == UserId())
                .FirstOrDefaultAsync(m => m.ID == id);

            return product == null ? NotFound() : (IActionResult)View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products
                                        .Where(i => i.FarmerId == UserId())
                                        .FirstOrDefaultAsync(m => m.ID == id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Farmer", new { id = UserId() });
            
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ID == id);
        }

        private string UserId()
        {
            return _userManager.GetUserId(HttpContext.User);
        }

        private Boolean IsProductOwn(string id)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            return userId == id ? true : false;
        }
    }
}

AgriFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgriFood</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/home.css" type="text/css">
    <link rel="stylesheet" href="~/css/farmer-detail.css" type="text/css">
    <link rel="stylesheet" href="~/css/account.css" type="text/css">
    <link rel="stylesheet" href="~/css/shared.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    
</head>
<body>
    <partial name="Partials/_Navbar" />
    <div class="container body-content">
        @RenderBody()
    </div>
    <partial name="Partials/_Footer" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true" defer></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AgriFood/Views/Shared/_ProductCard.cshtml
@model Product

<div class="m-4">
    <div class="product-card card">
    @if (Model.Image != null && Model.Image.Length > 0)
    {
        string imageSource = $"data:image;base64,{Convert.ToBase64String(@Model.Image)}";
        <img class="card-img-top" src="@imageSource" alt="Card image cap">
    }
    else
    {
      <img class="card-img-top" src="~/images/no_image.png" alt=@Model.Title>
    }
      <div class="card-body">
        <h5 class="card-title text-center">@Model.Title</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item text-center">Price: $@Model.Price</li>
        <li class="list-group-item text-center">
            <a asp-controller="Farmer" asp-action="Details" asp-route-id="@Model.Farmer.Id" 
            class="card-link">@Model.Farmer.FarmName</a>
        </li>
      </ul>
      <div class="card-body">
        <a asp-controller="Products" asp-action="Details" asp-route-id="@Model.ID" asp-route-FarmerId="@Model.FarmerId" 
        class="btn btn-primary btn-block text-center">Details</a>
      </div>
    </div>
</div>